//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.A1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о продажах.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОПродажах CustomAttributes)

    // *** End programmer edit section *** (ОтчетОПродажах CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о продажах")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОПродажахE", new string[] {
            "ДатаОкончания as \'Дата окончания\'",
            "ДатаНачала as \'Дата начала\'",
            "СумВклНДС as \'Сум вкл НДС\'",
            "СостОтгруз as \'Сост отгруз\'",
            "СостОплат as \'Сост оплат\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Подразеления as \'Подразеления\'",
            "Подразеления.Подразделение as \'Подразделение\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'"}, Hidden=new string[] {
            "Контрагенты.Контрагент",
            "Подразеления.Подразделение",
            "Организации.Организация",
            "Склады.Склад"})]
    [AssociatedDetailViewAttribute("ОтчетОПродажахE", "ТЧТоварИУслуг", "ТЧТоварИУслугE", true, "", "Т ч товар и услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтчетОПродажахE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [MasterViewDefineAttribute("ОтчетОПродажахE", "Подразеления", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Подразделение")]
    [MasterViewDefineAttribute("ОтчетОПродажахE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ОтчетОПродажахE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [View("ОтчетОПродажахL", new string[] {
            "ДатаОкончания as \'Дата окончания\'",
            "ДатаНачала as \'Дата начала\'",
            "СумВклНДС as \'Сум вкл НДС\'",
            "СостОтгруз as \'Сост отгруз\'",
            "СостОплат as \'Сост оплат\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Подразеления.Подразделение as \'Подразделение\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'"})]
    public class ОтчетОПродажах : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОкончания;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private int fСумВклНДС;
        
        private IIS.A1.СостОгрузки fСостОтгруз;
        
        private IIS.A1.СостОплаты fСостОплат;
        
        private IIS.A1.Контрагенты fКонтрагенты;
        
        private IIS.A1.Подразеления fПодразеления;
        
        private IIS.A1.Организации fОрганизации;
        
        private IIS.A1.Склады fСклады;
        
        private IIS.A1.DetailArrayOfТЧТоварИУслуг fТЧТоварИУслуг;
        
        // *** Start programmer edit section *** (ОтчетОПродажах CustomMembers)

        // *** End programmer edit section *** (ОтчетОПродажах CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаНачала Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаНачала Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаНачала Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаНачала Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаОкончания Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаОкончания Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаОкончания Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.ДатаОкончания Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// СостОплат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.СостОплат CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.СостОплат CustomAttributes)
        public virtual IIS.A1.СостОплаты СостОплат
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОплат Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОплат Get start)
                IIS.A1.СостОплаты result = this.fСостОплат;
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОплат Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОплат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОплат Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОплат Set start)
                this.fСостОплат = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОплат Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОплат Set end)
            }
        }
        
        /// <summary>
        /// СостОтгруз.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.СостОтгруз CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.СостОтгруз CustomAttributes)
        public virtual IIS.A1.СостОгрузки СостОтгруз
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОтгруз Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОтгруз Get start)
                IIS.A1.СостОгрузки result = this.fСостОтгруз;
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОтгруз Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОтгруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОтгруз Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОтгруз Set start)
                this.fСостОтгруз = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.СостОтгруз Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.СостОтгруз Set end)
            }
        }
        
        /// <summary>
        /// СумВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.СумВклНДС CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.СумВклНДС CustomAttributes)
        public virtual int СумВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.СумВклНДС Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.СумВклНДС Get start)
                int result = this.fСумВклНДС;
                // *** Start programmer edit section *** (ОтчетОПродажах.СумВклНДС Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.СумВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.СумВклНДС Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.СумВклНДС Set start)
                this.fСумВклНДС = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.СумВклНДС Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.СумВклНДС Set end)
            }
        }
        
        /// <summary>
        /// Отчет о продажах.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.Контрагенты CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.Контрагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагенты"})]
        [NotNull()]
        public virtual IIS.A1.Контрагенты Контрагенты
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Контрагенты Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.Контрагенты Get start)
                IIS.A1.Контрагенты result = this.fКонтрагенты;
                // *** Start programmer edit section *** (ОтчетОПродажах.Контрагенты Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.Контрагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Контрагенты Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.Контрагенты Set start)
                this.fКонтрагенты = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.Контрагенты Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.Контрагенты Set end)
            }
        }
        
        /// <summary>
        /// Отчет о продажах.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.Организации CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.A1.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Организации Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.Организации Get start)
                IIS.A1.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (ОтчетОПродажах.Организации Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Организации Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.Организации Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.Организации Set end)
            }
        }
        
        /// <summary>
        /// Отчет о продажах.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.Подразеления CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.Подразеления CustomAttributes)
        [PropertyStorage(new string[] {
                "Подразеления"})]
        [NotNull()]
        public virtual IIS.A1.Подразеления Подразеления
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Подразеления Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.Подразеления Get start)
                IIS.A1.Подразеления result = this.fПодразеления;
                // *** Start programmer edit section *** (ОтчетОПродажах.Подразеления Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.Подразеления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Подразеления Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.Подразеления Set start)
                this.fПодразеления = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.Подразеления Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.Подразеления Set end)
            }
        }
        
        /// <summary>
        /// Отчет о продажах.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.Склады CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.A1.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Склады Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.Склады Get start)
                IIS.A1.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ОтчетОПродажах.Склады Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.Склады Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.Склады Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.Склады Set end)
            }
        }
        
        /// <summary>
        /// Отчет о продажах.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг CustomAttributes)

        // *** End programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг CustomAttributes)
        public virtual IIS.A1.DetailArrayOfТЧТоварИУслуг ТЧТоварИУслуг
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Get start)

                // *** End programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Get start)
                if ((this.fТЧТоварИУслуг == null))
                {
                    this.fТЧТоварИУслуг = new IIS.A1.DetailArrayOfТЧТоварИУслуг(this);
                }
                IIS.A1.DetailArrayOfТЧТоварИУслуг result = this.fТЧТоварИУслуг;
                // *** Start programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Get end)

                // *** End programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Set start)

                // *** End programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Set start)
                this.fТЧТоварИУслуг = value;
                // *** Start programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Set end)

                // *** End programmer edit section *** (ОтчетОПродажах.ТЧТоварИУслуг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОПродажахE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОПродажахE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОПродажахE", typeof(IIS.A1.ОтчетОПродажах));
                }
            }
            
            /// <summary>
            /// "ОтчетОПродажахL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОПродажахL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОПродажахL", typeof(IIS.A1.ОтчетОПродажах));
                }
            }
        }
    }
}
