//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.A1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сост оплаты.
    /// </summary>
    // *** Start programmer edit section *** (СостОплаты CustomAttributes)

    // *** End programmer edit section *** (СостОплаты CustomAttributes)
    public enum СостОплаты
    {
        
        // *** Start programmer edit section *** (СостОплаты.Оплачен CustomAttributes)

        // *** End programmer edit section *** (СостОплаты.Оплачен CustomAttributes)
        Оплачен,
        
        // *** Start programmer edit section *** (СостОплаты.ЧастичноОплачен CustomAttributes)

        // *** End programmer edit section *** (СостОплаты.ЧастичноОплачен CustomAttributes)
        ЧастичноОплачен,
        
        // *** Start programmer edit section *** (СостОплаты.НеОплачен CustomAttributes)

        // *** End programmer edit section *** (СостОплаты.НеОплачен CustomAttributes)
        НеОплачен,
    }
}
